name: CI

on: [push, pull_request]

jobs:
  test-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Show environment
        run: |
          python -V
          pip -V
          echo "PWD=$(pwd)"
          ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Make src importable when running pytest (common CI gotcha)
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PWD/src:$PYTHONPATH" >> $GITHUB_ENV

      - name: Run tests
        run: |
          mkdir -p artifacts
          pytest -vv --maxfail=1 -rA | tee artifacts/pytest.log
        continue-on-error: false

      - name: Upload pytest log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-log
          path: artifacts/pytest.log
          if-no-files-found: warn

      - name: Run quick training
        if: ${{ success() }}
        run: |
          python src/train.py --version ci-test --model linear

      - name: Upload metrics artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: artifacts/metrics.json
          if-no-files-found: warn
